var goatNames = (function() {
    var billyNames = ["B.C.",
		      "Babauska",
		      "Babbelute",
		      "Babe",
		      "Babe Ruth",
		      "Babes",
		      "Baby Blanket",
		      "Baby Blue",
		      "Baby Boom",
		      "Baby Chick",
		      "Baby Doll",
		      "Baby Faith",
		      "Baby G",
		      "Baby Mae Bars",
		      "Baby Moon",
		      "Babycakes",
		      "Babycham",
		      "Bacardi",
		      "Back In A Flash",
		      "Back Splatter",
		      "Backstreet Bay",
		      "Bad Time",
		      "Bad Whisky",
		      "Badge",
		      "Badger",
		      "Bagels",
		      "Bail Me Out",
		      "Bailey",
		      "Baileys Irish Cream",
		      "Balancing Belle",
		      "Baldemar",
		      "Baldy",
		      "Ball Park",
		      "Ballerina",
		      "Ballet",
		      "Baloo",
		      "Bam-Bam",
		      "Bama",
		      "Bambi",
		      "Bambino",
		      "Bammer",
		      "Bandana",
		      "Bandido",
		      "Bandit",
		      "Banjo",
		      "Banner",
		      "Banner Blossom",
		      "Bar Code",
		      "Bar King",
		      "Bar Mount",
		      "Bar Room",
		      "Bar-K Truffles",
		      "Bare Necessities",
		      "Baringr",
		      "Barkley",
		      "Barleda",
		      "Barney",
		      "Barnum",
		      "Baron",
		      "Barq",
		      "Barreness",
		      "Barron",
		      "Bart",
		      "Baryshnikov",
		      "Barzanadana",
		      "Basha",
		      "Bashful",
		      "Basic Black",
		      "Basil",
		      "Basilas",
		      "Bask",
		      "Bassenthwaite",
		      "Bastiaan",
		      "Bathsheba",
		      "Batman",
		      "Batovian",
		      "Batteries Not Included",
		      "Battle Star",
		      "Battlecry",
		      "Batty",
		      "Baxter",
		      "Bay",
		      "Bay Of Biscayne",
		      "Bay Petite",
		      "Bayard",
		      "Bayjour",
		      "Baymont",
		      "Baystreet",
		      "Baywatch",
		      "Baywatch Babe",
		      "Bazooka",
		      "BBQ",
		      "Be My Guest",
		      "Be My Valentine",
		      "Beach",
		      "Beach Blanket Baby",
		      "Beach Game",
		      "Beachcomber",
		      "Beam Me Up Scottie",
		      "Beaming",
		      "Bear",
		      "Beat the Clock",
		      "Beau",
		      "Beau Dancer",
		      "Beau Zam",
		      "Beau Zephyr",
		      "Beautiful Dreamer",
		      "Beautiful Oblivian",
		      "Beauty",
		      "Beauty Queen",
		      "Beautys Star",
		      "Beaver",
		      "Beck",
		      "Bedazzaled",
		      "Beech Sky",
		      "Beezely",
		      "Beigh",
		      "Bekki",
		      "Believe",
		      "Believe n Miracles",
		      "Bell",
		      "Bella Baby",
		      "Bella Donna",
		      "Belladonte",
		      "Belle Flower",
		      "Belle Of Ireland",
		      "Belle of the Ball",
		      "Belle Of The Ball",
		      "Bellefire",
		      "Belleza",
		      "Bellini",
		      "Bellino",
		      "Bellotas Jewel",
		      "Belltello",
		      "Belly Dancer",
		      "Belmont",
		      "Ben",
		      "Benjamin",
		      "Benny",
		      "Benny Boy",
		      "Benson",
		      "Bento",
		      "Bermuda",
		      "Berry",
		      "Berry Blitz",
		      "Bert",
		      "Best Bet",
		      "Best of Luck",
		      "Beyond the Limits",
		      "Bianca",
		      "Big Bang Theory",
		      "Big Bear",
		      "Big Ben",
		      "Big Bert",
		      "Big Bird",
		      "Big Foot",
		      "Big Hustler",
		      "Big Jake",
		      "Big League",
		      "Big Mac",
		      "Big News",
		      "Big Red",
		      "Bign",
		      "Bigstone",
		      "Bijoux",
		      "Bikini",
		      "Bilbo",
		      "Billie",
		      "Billy",
		      "Billy the Kid",
		      "Bindi",
		      "Bindy",
		      "Bingo",
		      "Bio",
		      "Biraldo",
		      "Bird",
		      "Biscuit",
		      "Bistro",
		      "Bit of a Pickle",
		      "Bit of Masquerade",
		      "Bite My Dust",
		      "Bits",
		      "Bitsy",
		      "BJ",
		      "Black",
		      "Black Arts",
		      "Black Bar",
		      "Black Bart",
		      "Black Bear",
		      "Black Beauty",
		      "Black Belt",
		      "Black Bess",
		      "Black Cat",
		      "Black Cherry",
		      "Black Cloud",
		      "Black Diamond",
		      "Black Duchess",
		      "Black Fire",
		      "Black Flag",
		      "Black Forest Cake",
		      "Black Future",
		      "Black Gold",
		      "Black Heart",
		      "Black Is Black",
		      "Black Jack",
		      "Black Knight",
		      "Black Kyber",
		      "Black Label",
		      "Black Lace",
		      "Black Lightning",
		      "Black Magic",
		      "Black Mamba",
		      "Black Market",
		      "Black Olive",
		      "Black Operative",
		      "Black Ops",
		      "Black Pearl",
		      "Black Powder",
		      "Black Queen",
		      "Black Rose",
		      "Black Sabbath",
		      "Black Satin Pajamas",
		      "Black Shadows",
		      "Black Sheep",
		      "Black Showgirl",
		      "Black Snake",
		      "Black Swan",
		      "Black Tide",
		      "Black Tie",
		      "Black Tie Affair",
		      "Black Toes",
		      "Black Velvet",
		      "Black Watch",
		      "Black Widow",
		      "Black Zephyr",
		      "Blackbeard",
		      "Blackberry",
		      "Blackberry Stirrup",
		      "Blackeyed Pea",
		      "Blackhawk",
		      "Blackie",
		      "Blackjack",
		      "Blackout",
		      "Blacks Beach",
		      "Blacky",
		      "Blanca",
		      "Blanket Hog",
		      "Blanket Immunity",
		      "Blarney",
		      "Blaster",
		      "Blaze",
		      "Blaze of Enchantment",
		      "Blazing Berry",
		      "Blazing Comet",
		      "Blazing Heart",
		      "Blazing Keel",
		      "Blazing Speed",
		      "Blazing Star",
		      "Blessing",
		      "Blinding Beauty",
		      "Bling Bling",
		      "Bliss",
		      "Blissful",
		      "Blitz",
		      "Blitzen",
		      "Blizzard",
		      "Blonde Bombshell",
		      "Blonde Logic",
		      "Blondie",
		      "Blossom",
		      "Blue",
		      "Blue Angel",
		      "Blue Chip",
		      "Blue Cloud",
		      "Blue Eyed Bandit",
		      "Blue Eyes",
		      "Blue lands Rosey",
		      "Blue Legend",
		      "Blue Max",
		      "Blue Moon",
		      "Blue Murder",
		      "Blue Patent",
		      "Blue Stone",
		      "Blue Valentine",
		      "Bluebell",
		      "Blueberry Hill",
		      "BluebirdBluegrass",
		      "Blueprint",
		      "Blues Traveler",
		      "Blushing Beauty",
		      "Blustery",
		      "Bo",
		      "Bo Didley",
		      "Bo Hunk",
		      "Bob",
		      "Boba Fett",
		      "Bobbi",
		      "Bobbie",
		      "Bobby",
		      "Bobby Jo",
		      "Boe",
		      "Boiling Beauty",
		      "Bojangles",
		      "Bolaro",
		      "Bold Lad",
		      "Bold Venture",
		      "Bolero",
		      "Bolt",
		      "Bonnie Lass",
		      "Bonzo",
		      "Boo",
		      "Booger",
		      "Booger Baby",
		      "Boogie",
		      "Bookmark",
		      "Boomer",
		      "Boomerang",
		      "Boots",
		      "Boots Scootn",
		      "Born To Be Bad",
		      "Born To Do It",
		      "Born To Fly",
		      "Bossinova",
		      "Bossy",
		      "Boston",
		      "Boston Cream",
		      "Botanic",
		      "Bounty",
		      "Bourbon",
		      "Bow",
		      "Bow Tie",
		      "Boy",
		      "Bracken",
		      "Bramble",
		      "Branagan",
		      "Brandon",
		      "Brandy",
		      "Brash n Sassy",
		      "Brass Plum",
		      "Brat",
		      "Brave",
		      "Brave One",
		      "Brave Vision",
		      "Braveheart",
		      "Bravo",
		      "Breeze",
		      "Breeze Bar",
		      "Breeze of the South",
		      "Breezy",
		      "Breman",
		      "Brenner",
		      "Brewski",
		      "Brianna",
		      "Bridal Run",
		      "Bridle Of Frankenstein",
		      "Bridle Veil",
		      "Brie",
		      "Brigham",
		      "Bright Idea",
		      "British Banker",
		      "Britt",
		      "Brocco",
		      "Broken Arrow",
		      "Broker",
		      "Bronson",
		      "Bronze Cross",
		      "Bronze Medalist",
		      "Brook",
		      "Brooke",
		      "Brown",
		      "Brown Betty",
		      "Brown Sugar",
		      "Brownie",
		      "Bruce",
		      "Bruiser",
		      "Brunello",
		      "Bruno",
		      "Brutus",
		      "Buba",
		      "Bubba",
		      "Bubble",
		      "Bubble Gum",
		      "Bubbles",
		      "Bubs",
		      "Buck",
		      "Buck of Sugar",
		      "Buck Or Two",
		      "Buck-A-Roo",
		      "Buckeroo Times Two",
		      "Buckminster",
		      "Buckshot",
		      "Buckwheat",
		      "Bucky",
		      "Bud",
		      "Buddy",
		      "Budha",
		      "Bueno",
		      "Buffy",
		      "Bugaboo",
		      "Bugs",
		      "Bugs Bunny",
		      "Bugsy",
		      "Bull Marker",
		      "Bullet",
		      "Bullseye",
		      "Bullwinkle",
		      "Bumble",
		      "Bumble Bee",
		      "Bumbles",
		      "Bumper",
		      "Bumpkin",
		      "Bumpy",
		      "Bunny",
		      "Burgandy Rose",
		      "Burning Man",
		      "Burst of Stardust",
		      "Busco",
		      "Buster",
		      "Butter",
		      "Butterball",
		      "Buttercup",
		      "Butterfly",
		      "Butterfly Kisses",
		      "Buttermilk",
		      "Butterscotch",
		      "Butterworth",
		      "Buttons",
		      "Buttons And Bows",
		      "Buzz",
		      "Buzz Lightyear"];
    var nannyNames = ["Nabisco",
		      "Nabisco Cracker",
		      "Nabrina",
		      "Nadia",
		      "Nadine Novelle",
		      "Naduah Mccue",
		      "Nafa",
		      "Nakima",
		      "Naksup",
		      "Nanook",
		      "Napoleon",
		      "Naraskanaia",
		      "Narita",
		      "Narnia",
		      "Nash",
		      "Natalie",
		      "Natasha",
		      "Nate",
		      "Nates Nikes",
		      "Natiqua",
		      "Natural Blonde",
		      "Natural Element",
		      "Natural Pearl",
		      "Natures Basics",
		      "Nautical Adventure",
		      "Navaho",
		      "Navajo",
		      "Navar",
		      "Navigator",
		      "Nearly perfect",
		      "Ned",
		      "Neealba",
		      "Nellie",
		      "Nelly",
		      "Nelson",
		      "Nemo",
		      "Neon",
		      "Neptune",
		      "Neriffe",
		      "Nero",
		      "Netty",
		      "Nevada",
		      "Nevada Sky",
		      "Nevaeh Sky",
		      "Nevarra",
		      "Never say Never",
		      "Nevertheless",
		      "New Hope",
		      "New Moon",
		      "New York Minute",
		      "Niagara",
		      "Nibbles",
		      "Nibbley",
		      "Nibby",
		      "Nick",
		      "Nicker To Me",
		      "Nicki",
		      "Nickles n Dimes",
		      "Nicole",
		      "Nifty",
		      "Night At The Opera",
		      "Night Chronicles",
		      "Night Dancer",
		      "Night Flight",
		      "Night Out",
		      "Night Raven",
		      "Night Rider",
		      "Night Show",
		      "Night Stalker",
		      "Night Train",
		      "Night Watchman",
		      "Night Wind",
		      "Nighthawk",
		      "Nightingale",
		      "Nightlight",
		      "Nightwing",
		      "Nikes New Found Glory",
		      "Nikita",
		      "Nikki",
		      "Niko",
		      "Nila Skips Cool",
		      "Nilly",
		      "Nimaway",
		      "Nimbus",
		      "Nimfo Noon",
		      "Ninjo",
		      "Nirvana",
		      "Nitro",
		      "No Fear",
		      "No Regrets",
		      "Noble",
		      "Noel",
		      "Nor",
		      "Nordance Prince",
		      "NorEaster",
		      "Northen star",
		      "Northern Lights",
		      "Norton",
		      "Nosey",
		      "Not At the Moment",
		      "Not Exactly Monday",
		      "Nothin But Trouble",
		      "Notorious",
		      "Notorized Kate",
		      "Nottachance",
		      "Nougat",
		      "November Rain",
		      "Now or never",
		      "Nuala",
		      "Nubias Princess",
		      "Nugget",
		      "Nutcracker",
		      "Nutmeg",
		      "Nuts",
		      "Nutty"];

    function pickName(gender) {
	var namesArray = (gender == "M" ? billyNames : nannyNames);
	var randIndex = Math.floor(Math.random() * namesArray.length);

	return namesArray[randIndex];
    }

    return { pickName: pickName };
})();

module.exports = goatNames;
