var socketServer = function() {
    var data = null,
        timerID = null,
        sockets = [],
	socketServer = null,
	ws = require('engine.io'),
	http = require('http'),
	fs = require('fs'),
	url = require('url'),
	domain = require('domain'),
	reqDomain = domain.create(),
	socketDomain = domain.create(),
	httpDomain = domain.create(),

	httpListen = function (port) {
	    httpDomain.on('error', function (err) {
		console.log('Error caught in http domain:' + err);
	    });

	    httpDomain.run(function () {
		http.createServer(function (req, res) {
		    var pathname = url.parse(req.url).pathname;
		    console.log(pathname);
		    if (pathname == '/' || pathname == '/index.html') {
			readFile(res, 'index.html');
		    }
		    else {
			readFile(res, '.' + pathname);
		    }
		}).listen(port);
	    });
	},

	readFile = function(res, pathname) {
	    fs.readFile(pathname, function (err, data) {
		if (err) {
		    console.log(err.message);
		    res.writeHead(404, {'content-type': 'text/html'});
		    res.write('File not found: ' + pathname);
		    res.end();
		}
		else {
		    res.write(data);
		    res.end();
		}
	    });       
	},

	socketListen = function(port) {
	    socketDomain.on('error', function(err) {
		console.log('Error caught in socket domain:' + err);
	    });

	    socketDomain.run(function() { 
		socketServer = ws.listen(port);

		socketServer.on('listening',function(){
		    console.log('SocketServer is running');
		});

		socketServer.on('connection', function (socket) {

		    console.log('Connected to client');
		    sockets.push(socket);
		    if (data == null) getQuotes();

		    socket.on('message', function (data) { 
			console.log('Message received:', data);
		    });

		    socket.on('close', function () {
			try {
			    socket.close();
			    socket.destroy();
			    console.log('Socket closed!');                       
			    for (var i = 0; i < sockets.length; i++) {
				if (sockets[i] == socket) {
				    sockets.splice(i, 1);
				    console.log('Removing socket from collection. Collection length: ' + sockets.length);
				    break;
				}
			    }
                            
			    if (sockets.length == 0) {
				clearInterval(timerID);
				data = null;
			    }
			}
			catch (e) {
			    console.log(e);
			}
		    });

		});  
	    });      
	},

	getQuotes = function() {
	    var quotes = [
		"I don't deserve this award, but I have arthritis and I don't deserve that either.",
		"I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living, it's a way of looking at life through the wrong end of a telescope. Which is what I do, and that enables you to laugh at life's realities.",
		"There is a road, no simple highway, between the dawn and the dark of night, and if you go, no one may follow, that path is for your steps alone.",
		"I wonder if I shall fall right through the earth! How funny it'll seem to come out among the people that walk with their heads downward!",
		"The world is a looking glass, and gives back to every man the reflection of his own face. Frown at it and it will in turn look sourly upon you; laugh at it and with it, and it is a jolly kind companion.",
		"People who know little are usually great talkers, while men who know much say little.",
		"A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
		"I've had a lover's quarrel with the world.",
		"I'd rather be a failure at something I love than a success at something I hate.",
		"No pessimest ever discovered the secrets of the stars, or sailed to an uncharted land, or opened a new heaven to the human spirit.",
		"One ought, every day at least, to hear a little song, read a good poem, see a fine picture and, if possible, speak a few reasonable words.",
		"It is normal to give away a little of one's life in order not to lose it all.",
		"Three o'clock is always too late or too early for anything you want to do.",
		"Do, or do not. There is no 'try'.",
		"Poetry and Hums aren't things which you get, they're things which get you. And all you can do is to go where they can find you.",
		"Finish each day and be done with it. Youhave done what you could; some blunders and absurdities have crept in;  forget them as soon as you can. Tomorrow is a new day; you shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.",
		"Old boys have their playthings as well as young ones, the difference is only in the price.",
		"Little surprises around everywhere, but nothing dangerous. Don't be alarmed.",
		"It's not very pleasant in my corner of the world at three o'clock in the morning. But for people who like cold, wet, ugly bits it is something rather special.",
		"There was a man from Sung who pulled at his rice plants because he was worried about their failure to grow.",
		"There were many ways of breaking a heart. Stories were full of hearts being broken by love, but what really broke a heart was taking away its dream - whatever that dream might be.",
		"I had rather attempt something great and fail, than to attempt nothing at all and succeed.",
		"If I had my life to live over, I would try to make more mistakes.  I would relax. I would climb more mountains and swim more rivers. I would pick more daisies. I would have more actual troubles and fewer imaginary ones.",
		"The greatest pleasure in life is doing what people say you cannot do.",
		"There is no cure for birth and death save to enjoy the interval.",
		"We rest here while we can, but we hear the ocean calling in our dreams, And we know by the morning, the wind will fill our sails to test the seams, The calm is on the water and part of us would linger by the shore, For ships are safe in harbor, but that's not what ships are for.",
		"Analysis kills spontaneity. The grain once ground into flour springs and germinates no more.",
		"The game of life is not so much in holding a good hand as playing a poor hand well.",
		"One person with a belief is equal to a force of 99 who have only interests.",
		"You will never be happy if you continue to search for what happiness consists of.  You will never live if you are looking for the meaning of life.",
		"The sharp edge of a razor is difficult to pass over;  thus the wise say the path to Salvation is hard.",
		"I divide my time as follows: half the time I sleep, the other half I dream. I never dream when I sleep, for that would be a pity, for sleeping is the highest accomplishment of genius.",
		"The greatest mistake you can make in life is to be continually fearing you will make one.",
		"It is not necessary that you leave the house. Remain at your table and listen. Do not even listen,  only wait. Do not even wait, be wholly still and alone. The world will present itself to you for its unmasking . . . in ecstasy it will writhe at your feet.",
		"Only those who dare to fail greatly can ever achieve greatly.",
		"I have seen yesterday, I love today, I am not afraid of tomorrow.",
		"I don't think there ever was a lazy man in this world. Every man has some sort of gift, and he prizes that gift beyond all others. He may be a professional billiard-player, or a Paderewski, or a poet - I don't care what it is. But whatever it is, he takes a native delight in exploiting that gift, and you will find it is difficult to beguile him away from it. Well, there are thousands of other interests occupying other men, but those interests don't appeal to the special tastes of the billiard champion or Paderewski. They are set down, therefore, as too lazy to do that or do this - to do, in short what they have no taste or inclination to do. In that sense, then I am phenomenally lazy. But when it comes to writing a book - I am not lazy. My family find it difficult to dig me out of my chair.",
		"I have learned at least this by my experiments: that if one advances confidenly in the direction of his dreams and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.",
		"If nothing in life is a struggle then life itself will become one.",
		"A man walks through life painting a portrait, not of what he would have done, could have done, or should have done, but of what he did.",
		"Do Not follow where the path may lead.  Go instead where there is no path, and leave a trail.",
		"All the Woulda-Coulda-Shouldas Layin' in the sun, Talkin' bout the things They woulda-coulda-shoulda done... But those Woulda-Coulda-Shouldas All ran away and hid From one little did.",
		"Joy, temperance, and repose, Slam the door on the doctor's nose.",
		"When they leave here they'll be completely restored to their normal terrible old selves. But maybe they'll be a little wiser for the wear.",
		"Thats always been my problem.  People think I'm being vulgar when I'm being serious and serious when I'm being vulgar.",
		"The man on top of the mountain did not fall there.",
		"Come to the edge, he said.  We are afraid, they said.  Come to the edge, he said.  They came, he pushed...and they flew.",
		"You should never doubt what no one is sure about.",
		"We are the music makers, and we are the dreamers of dreams.",
		"A mistake in judgment isn't fatal, but too much anxiety about judgment is.",
		"Security is mostly a superstition. It does not exist in nature, nor do the children of men as a whole experience it. Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure or nothing.",
		"There is no course of life so weak and sottish as that which is managed by order, method, and discipline.",
		"Take your time, think a lot, think of everything you've got.  For you will still be here tomorrow nut your dreams may not.",
		"Youth furnishes the materials and plans for the future.  Maturity takes and cuts the stones; provided the so-called wisdom of old age doesn't destroy the genius of youth.",
		"I believe in getting into hot water; it keeps you clean.",
		"I sit beside the fire and think of all that I have seen, of meadow-flowers and butterflies.  In summers that have been;  Of yellow leaves and gossamer in autumns that there were, with morning mist and silver sun and wind upon my hair.",
		"The world stands aside to let anyone pass who knows where he is going.",
		"The activity of happiness must occupy an entire lifetime; for one swallow does not a summer make.",
		"Today equals the sum of yesterdays dreams and tomorrows memories.",
		"There are those that look at things the way they are, and ask why? I dream of things that never were, and ask why not.",
		"Serious-minded people have few ideas. People with ideas are never serious.",
		"You'll miss 100% of all the shots you don't take.",
		"To live you have to experiment, to have the ability to experiment you have to have confidence, to have confidence you have to be loved, to be loved you have to love.",
		"When I'm playful I use the meridians of longitude and parallels of latitude for a seine, and drag the Atlantic Ocean for whales. I scratch my head with the lightning and purr myself to sleep with the thunder.",
		"The troubles of the young are soon over; they leave no external mark. If you wound the tree in its youth the bark will quickly cover the gash; but when the tree is very old, peeling the bark off . . . you will see the scar there still.",
		"Everything has two sides --the outside that is ridiculous, and the inside that is solemn.",
		"People tend to think that life really does progress for everyone eventually, that people progress, but actually only some people progress. The rest of the people don't.",
		"The quality of life is determined by its activities",
		"I was wise enough to never grow up while fooling most people into believing I had.",
		"What lies behind us and what lies before us are tiny matters compared to what lies within us.",
		"Skate to where the puck is going, not to where it's been",
		"When you remember how hard it is to change yourself, you begin to understand what little chance we have of changing others.",
		"Before I knew the best part of my life had come, it had gone.",
		"After a time, you may find that \"having\" is not so pleasing a thing, after all, as \"wanting.\" It is not logical, but it is often true.",
		"We don't live in the world of reality, we live in the world of how we perceive reality.",
		"The common ingredients of health and long life are: Great temperance, open air, Easy labor and little care.",
		"There is no such thing as a sudden heart-attack. It takes years of preparation.",
		"What a pity human beings can't exchange problems. Everyone knows exactly how to solve the other fellow's.",
		"Look not mournfully into the Past. It comes not back again. Wisely improve the Present. In is thine. Go forth to meet the shadowy Future, without fear, and a manly heart.",
		"Anybody can win unless there happens to be a second entry.",
		"Today is cash, tomorrow is a promissary note.",
		"It all comes down to one very simple choice.... Get busy livin' or get busy dyin'.",
		"If a little dreaming is dangerous, the cure for it is not to dream less but to dream more, to dream all the time.",
		"Whenever I climb I am followed by a dog called 'Ego'.",
		"Little things console us because little things afflict us.",
		"It was previously a question of finding out whether or not life had to have a meaning to be lived. It now  becomes clear, on the contrary, that it will be lived all the better if it has no meaning.",
		"The most beautiful thing we can experience is the mysterious. It is the source of all true art and all science. He to whom this emotion is a stranger, who can no longer pause to wonder and stand rapt in awe, is as good as dead; his eyes are closed.",
		"There is a theory which states that if ever anybody discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable.  There is another theory which states that this has already happened.",
		"The greatest trick the devil ever played was convincing the world he didn't exist.",
		"He who stands of tiptoe is not steady.  He who strides cannot maintain the pace.",
		"Man drives, but the Creator holds the reigns.",
		"Those who dream by day are cognizant of many things that escape those who dream only at night.",
		"The devil can site Scripture for his purpose.",
		"Eventually, all things merge into one, and a river runs through it.  The river was cut by the world's great flood and runs over rocks from the basement of time.  On some of the rocks are timeless raindrops.  Under the rocks are the words, and some of the words are theirs.",
		"To swear off making mistakes is very easy. All you have to do is swear off having ideas.",
		"The world owes all its onward impulses to men ill at ease. The happy man confines himself within ancient limits.",
		"Talk about your plenty, talk about your ills, One man gathers what another man spills.",
		"Hold fast to dreams , for if dreams die, life is like a broken winged bird that cannot fly.",
		"There is a time for departure even when there's no certain place to go.",
		"I live in that solitude which is painful in youth, but delicious in the years of maturity.",
		"The noisiest drum has nothing in it but air.",
		"Still round the corner there may wait, A new road or a secret gate.",
		"We cannot tempt fate without eventually getting scorched by it.",
		"Hope is a good thing - maybe the best thing, and no good thing ever dies.",
		"Reach high, for stars lie hidden in your soul.  Dream deep, for every dream precedes the goal.",
		"Age does not bring wisdom ... but it does give perspective . . . and the saddest perspective of all is to see far, far behind you, the temptations you've passed up.",
		"Heaven never helps the men who will not act.",
		"The sage manages affairs without action and spreads doctrines without words . . .  By acting without action, all things will be in order.",
		"The sole root of mans' unhappiness is that man does not know how to sit and stay quietly in his room",
		"Smooth seas do not make skillful sailors.",
		"Often people attempt to live their lives backwards; they try to have more things, or more money, in order to do more of what they want, so they will be happier. The way it actually works is the reverse. You must first be who you really are, then do what you need to do, in order to have what you want.",
		"When a man won't listen to his conscience, it's usually because he doesn't want advice from a total stranger.",
		"There comes a time when suddenly you realize that laughter is something you remember and that you were the one laughing.",
		"There are too many books I haven't read, too many places I haven't seen, too many memories I haven't kept long enough.",
		"Time does not relinquish its rights, either over human beings or over mountains.",
		"If you stop searching, you stop living, because then you're dwelling in the past. If you're not reaching forward to any growth or future, you might as well be dead.",
		"Life only demands from you the strength you possess.   Only one feat is possible.  Not to have run away.",
		"Don't take life too seriously. You'll never get out alive.",
		"Everything that irritates us about others can lead us to an understanding of ourselves.",
		"It's never to late to have a happy childhood.",
		"You can't depend on your eyes when your imagination is out of focus.",
		"To be what we are, and to become what we are capable of becoming, is the only end of life.",
		"While one person hesitates because he feels inferior, the other is busy making mistakes and becoming superior.",
		"The story teller makes no choice. Soon you will not hear his voice.  His job is to shed light, and not to master.  Since the end is never told, we pay the teller off in gold, in hopes he will return, but he cannot be bought or sold.",
		"It is better to be high-spirited even though one makes more mistakes, than to be narrow-minded and all to prudent.  Do not quench your inspiration and your imagination; do not become the slave of your model.",
		"If everything's under control, you're going too slow.",
		"No matter how far you have gone on the wrong road, turn back.",
		"Do all the good you can, By all the means you can, In all the ways you can, In all the places you can, At all the times you can, To all the people you can, As long as ever you can.",
		"One lives in the hope of becoming a memory.",
		"In raising my children, I have lost my mind but found my soul.",
		"You can outdistance that which is running after you, but not what is running inside you.",
		"If you think nobody cares if you're alive, try missing a couple of car payments.",
		"One day at a time -- this is enough. Do not look back and grieve over the past, for it is gone; and do not be troubled about the future, for it has not yet come. Live in the present, and make it so beautiful that it will be worth remembering.",
		"A man who is 'of sound mind' is one who keeps the inner madman under lock and key.",
		"You grow up the day you have your first real laugh -- at yourself.",
		"A positive attitude may not solve all your problems, but it will annoy enough people to make it worth the effort.",
		"A hundred years from now it will not matter what my bank account was, the sort of house I lived in, or the kind of car I drove... But the world may be different because I was important in the life of a child.",
		"The only Zen you find on the tops of mountains is the Zen you bring up there.",
		"Remain calm, serene, always in command of yourself. You will then find out how easy it is to get along.",
		"Sooner or later we must realize there is no station, no one place to arrive at once and for all. The true joy of life is the trip.",
		"If you want your dreams to come true, don't sleep.",
		"The minute you settle for less than you deserve, you get even less than you settled for.",
		"Ideas are like wandering sons. They show up when you least expect them.",
		"Dreams are renewable. No matter what our age or condition, there are still untapped possibilities within us and new beauty waiting to be born.",
		"When you finally go back to your old hometown, you find it wasn't the old home you missed but your childhood.",
		"Among my most prized possessions are words that I have never spoken.",
		"Seek freedom and become captive of your desires. Seek discipline and find your liberty.",
		"Isolation is aloneness that feels forced upon you, like a punishment. Solitude is aloneness you choose and embrace. I think great things can come out of solitude, out of going to a place where all is quiet except the beating of your heart.",
		"On the whole, age comes more gently to those who have some doorway into an abstract world-art, or philosophy, or learning-regions where the years are scarcely noticed and the young and old can meet in a pale truthful light.",
		"To rid ourselves of our shadows - who we are - we must step into either total light or total darkness.",
		"Happy campers you have been, happy campers you are, and happy campers you will always be.",
		"Millions long for immortality who do not know what to do with themselves on a rainy Sunday afternoon.",
		"I like to see you move with the rythm; I Like to see when you're dancin' from within.",
		"There is only one corner of the universe you can be certain of improving and that is your own self.",
		"He who wonders discovers that this in itself is wonder.",
		"A good traveler has no fixed plans, and is not intent on arriving.",
		"It is the sign of a dull mind to dwell upon the cares of the body, to prolong exercise, eating and drinking, and other bodily functions. These things are best done by the way; all your attention must be given to the mind.",
		"Life beats down and crushes the soul and art reminds you that you have one.",
		"One of the advantages of being disorderly is that one is constantly making exciting discoveries.",
		"As soon as man does not take his existence for granted, but beholds it as something unfathomably mysterious, thought begins.",
		"Reality is merely an illusion, albeit a very persistent one.",
		"If a person foolishly does me wrong, I will return to him the protection of my boundless love. The more evil that comes from him, the more good will go from me. I will always give off only the fragrance of goodness.",
		"This occupation with ideas of immortality is for people of rank, and especially for ladies who have nothing to do.  But a man of real worth who has something to do here, and must toil and struggle to produce day by day, leaves the future world to itself, and is active and useful in this.",
		"A wee child toddling in a wonder world, I prefer to their dogma my excursions into the natural gardens where the voice of the Great Spirit is heard in the twittering of birds, the rippling of mighty waters, and the sweet breathing of flowers. If this is Paganism, then at present, at least, I am a Pagan.",
		"If you think you're too small to have an impact, try going to bed with a mosquito in the room.",
		"The hearts of the great can be changed.",
		"Never let the future disturb you.  You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
		"The man who insists upon seeing with perfect clearness before he decides, never decides. Accept life and you must accept regret.",
		"Make the best use of what is in your power, and take the rest as it happens.",
		"Let yourself be open and life will be easier.  A spoon of salt in a glass of water makes the water undrinkable.  A spoon of salt in a lake is almost unnoticed.",
		"The worst things: To be in bed and sleep not, To want for one who comes not, To try to please and please not.",
		"Sanity is madness put to good uses; waking life is a dream controlled.",
		"Ventis secundis, tene cursum.",
		"Even in the presence of others, he was completely alone.",
		"Talk to every woman as if you loved her, and to every man as if he bored you, and at the end of your first season you will have the reputation of possessing the most perfect social tact.",
		"When a child asks you something, answer him, for goodness sake. But dont make a production of it. Children are children, but they can spot an evasion quicker than adults, and evasion simply muddles em.",
		"Be aware that young people have to be able to make their own mistakes and that times change.",
		"A daydream is a meal at which images are eaten. Some of us are gourmets, some gourmands, and a good many take their images precooked out of a can and swallow them down whole, absent-mindedly and with little relish.",
		"A man is not honest simply because he never had a chance to steal.",
		"The death of fear is in doing what you fear to do.",
		"Men create war to compete with women, who create life.",
		"A man dies still if he has done nothing, as one who has done much.  ",
		"The misfortune of the wise is better than the prosperity of the fool.",
		"To accuse others for one's own misfortunes is a sign of want of education.   To accuse oneself shows that one's education has begun.  To accuse neither  oneself nor others shows that one's education is complete.",
		"A conservative is a man with two perfectly good legs who, however, has never learned how to walk forward.",
		"I'm a simple man. All I want is enough sleep for two normal men, enough whiskey for three, and enough women for four.",
		"Excess on occasion is exhilarating. It prevents moderation from acquiring the deadening effect of a habit.",
		"The sweetest of all sounds is praise.",
		"My opinions may have changed, but not the fact that I'm right.",
		"Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.",
		"The will to win is worthless if you don't get paid for it.",
		"In the fight between you and the world, back the world.",
		"Every man alone is sincere; at the entrance of a second person hypocrisy begins.",
		"I enjoyed my own nature to the fullest, and we all know that there lies happiness, although, to soothe one another mutually, we occasionally pretend to condemn such joys as selfishness.",
		"I seated ugliness on my knee, and almost immediately grew tired of it.",
		"Everything has been figured out, except how to live.",
		"We should consider every day lost on which we have not danced at least once. And we should call every truth false which was not accompanied by at least one laugh.",
		"Objective evidence and certitude are doubtless very fine ideals to play with, but where on this moonlit and dream-visited planet are they found?",
		"Patience will achieve more than force.",
		"If you believe everything you read, you better not read.",
		"Against stupidity the very gods themselves contend in vain.",
		"When you live in the shadow of insanity, the appearance of another mind that thinks and acts as yours does is something close to a blessed event.",
		"Failures are divided into two classes--those who thought and never did, and those who did and never thought.",
		"Keep cool, but don't freeze.",
		"Words - so innocent and powerless as they are, as standing in a dictionary, how potent for good and evil they become in the hands of one who knows how to combine them.",
		"You can cheat an honest man but not make a fool out of him.",
		"You've got to be careful if you don't know where you are going, because you might not get there.",
		"A child of five would understand this. Send someone to fetch a child of five.",
		"By the time a man realizes that maybe his father was right, he usually has a son who thinks he's wrong.",
		"If you want a place in the sun you've got to put up with a few blisters",
		"The only limits are, as always, those of vision.",
		"In three words I can sum up everything I've learned about life.  It goes on.",
		"Accept that some days you're the pigeon, and some days your're the statue.",
		"Better to be occasionally cheated than prpetually suspicious.",
		"Thing big thoughts but relish small pleasures.",
		"Success is how high you bounce when you hit bottom.",
		"A man's greatest strength develops at the point where he overcomes his greatest weakness.",
		"Between two evils, I always pick the one I never tried before.",
		"The moment of victory is much too short to live for that and nothing else.",
		"Perseverence is not a long race; it is many short races one after another.",
		"Inorder to make your dreams come true, you must awaken and take charge.",
		"I was too far out all my life, and not waving, but drowning.",
		"The mind makes a self made prison, while the heart makes a self taught lover.",
		"Silence is the haven of a purposeful mind.",
		"Poetry is the key to one of lifes biggest mysteries; the human mind.",
		"Never eat more than you can lift.",
		"Counting time is not so important as making time count.",
		"I can accept failure. Everyone fails at something. But l can't accept not trying.",
		"Once you face your fear, nothing is ever as hard as you think.",
		"If you plan for the worse and the worst does not come, what does come is at least better.",
		"We just don't recognize the most significant moments of our lives while they're happening.",
		"We don't change over time. We only become more ourselves.",
		"A journey of a thousand miles begins with one simple step.",
		"Failure is a word I simply don't accept!",
		"Don't feel sorry for yourself if you have taken the wrong road - turn around!",
		"Work like you don't need the money, love like you've never been hurt, and dance like no one is watching...",
		"God made the world, My Lord, and looked at it, and saw that it was good. Yes. But what if the world had looked back at him, to see whether he was goodor not?",
		"I thought for a minute, and I said, Well, I wanted to be a beautiful pearl, but I looked in the mirror and decided that wasn't in the cards. And then I said, Oh, well, maybe I can be an oyster, because the oyster makes the beautiful pearl.",
		"Remember not only to say the right thing in the right place, but far more difficult still, to leave unsaid the wrong thing at the tempting moment.",
		"Everyone has talent. What is rare is the courage to follow the talent to the dark place where it leads.",
		"Someone's boring me. I think it's me.",
		"The average person thinks he isn't.",
		"Your true value depends entirely on what you are compared with.",
		"Even if you're on the right track, you'll get run over if you just sit there.",
		"Truly great madness cannot be achieved without significant intelligence.",
		"Imagination is the one weapon in the war against reality.",
		"The most wasted of all days is one without laughter.",
		"In these matters the only certainty is that nothing is certain.",
		"Always and never are two words you should always remember never to use.",
		"There is no such thing as a 'self-made' man. We are made up of thousands of others. Everyone who has ever done a kind deed for us, or spoken one word of encouragement to us, has entered into the make-up of our character and of our thoughts, as well as our success.",
		"The work goes on, the cause endures, the hope still lives and the dreams shall never die.",
		"Freedom is not worth having if it does not include the freedom to make mistakes.",
		"We learn from experience that men never learn anything from experience.",
		"Our lives improve only when we take chances -- and the first and most difficult risk we can take is to be honest with ourselves.",
		"If people did not sometimes do silly things, nothing intelligent would ever get done.",
		"I want to stay as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.",
		"Some of the world's greatest feats were accomplished by people not smart enought to know they were impossible.",
		"There's no fool like an old fool --- you can't beat experience.",
		"Every generation thinks it has the answers, and every generation is humbled by nature.",
		"No man really becomes a fool until he stops asking questions.",
		"The man who views the world at 50 the same as he did at 20 has wasted 30 years of his life.",
		"An unfortunate thing about this world is that the good habits are much easier to give up than the bad ones.",
		"A man is a success if he gets up in the morning and gets to bed at night, and in between he does what he wants to do.",
		"It wasn't until late in life that I discovered how easy it is to say 'I don't know'.",
		"There's only one corner of the universe you can be certain of improving, and that's your own self.",
		"If you can spend a perfectly useless afternoon in a perfectly useless manner, you have learned how to live.",
		"Excess on occasion is exhilarating. It prevents moderation from acquiring the deadening effect of a habit.",
		"Consider the postage stamp: its usefulness consists in the ability to stick to one thing till it gets there.",
		"Some people come into our lives and quickly go. Others stay for a while and leave footprints on our hearts and we are never the same.",
		"I'm goin' where the wind don't blow so strange, maybe off on some high cold mountain chain.",
		"In order to make your dreams come true, you must awaken and take charge.",
		"I was too far out all my life, and not waving, but drowning.",
		"The mind makes a self made prison, while the heart makes a self taught lover.",
		"Silence is the haven of a purposeful mind.",
		"Once you face your fear, nothing is ever as hard as you think.",
		"We have two ears and one mouth so that we can listen twice as much as we speak.",
		"In the depth of winter, I finally learned that within me there lay an invincible summer.",
		"If you plan for the worse and the worst does not come, what does come is at least better.",
		"We just don't recognize the most significant moments of our lives while they're happening.",
		"That man is the richest whose pleasures are the cheapest.",
		"Don't feel sorry for yourself if you have taken the wrong road - turn around!",
		"Remember not only to say the right thing in the right place, but far more difficult still, to leave unsaid the wrong thing at the tempting moment.",
		"Everyone has talent. What is rare is the courage to follow the talent to the dark place where it leads.",
		"Your true value depends entirely on what you are compared with.",
		"Truly great madness cannot be achieved without significant intelligence.",
		"The most wasted of all days is one without laughter.",
		"The work goes on, the cause endures, the hope still lives and the dreams shall never die.",
		"We learn from experience that men never learn anything from experience.",
		"Our lives improve only when we take chances -- and the first and most difficult risk we can take is to be honest with ourselves.",
		"If people did not sometimes do silly things, nothing intelligent would ever get done.",
		"I want to stay as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.",
		"If you are drowning and all you can think about is the fact that you can't swim, you are certainly going to die.",
		"Life is like a rollercoaster, it has it's ups and downs, but when part of it is over, you wish you could do it again.",
		"In order to live free and happily you must sacrifice boredom. It is not always an easy sacrifice.",
		"Habits are safer than rules; you don't have to watch them. And you don't have to keep them either. They keep you.",
		"Every normal man must be tempted, at times, to spit on his hands, hoist the black flag, and begin slitting throats.",
		"They may forget what you said, but they will never forget how you made them feel.",
		"A cynic is a person searching for an honest man, with a stolen lantern.",
		"It's hard to fight an enemy who has outposts in your head.",
		"It is better to be defeated on principle than to win on lies.",
		"You can get much farther with a kind word and a gun than you can with a kind word alone.",
		"You cannot prevent the birds of sorrow from flying over your head, but you can prevent them from building nests in your hair.",
		"Nicht wollen ist der Grund, nicht knnen nur der Vorwand.",
		"Somehow life doesn't always pay off to those who are most insistent.",
		"It ain't no sin to be glad you're alive.",
		"Making a record is like building a ship in a bottle. Playing a concert is like being in a rowboat on the ocean.",
		"Be sure you put your feet in the right place, then stand firm.",
		"To make a prairie, It takes clover and one bee, One clover, and a bee, and revery.  The revery alone will do, If bees are few.",
		"Only those who attempt the absurd will achieve the impossible.  I think it's in my basement...let me go upstairs and check.",
		"Don't cry when the sun is gone, because the tears won't let you see the stars.",
		"Always go to the bathroom when you have a chance.",
		"We must laugh at man to avoid crying for him.",
		"I have never been lost, but I will admit to being confused for several weeks.",
		"The man who rolls up his sleeves seldom loses his shirt.",
		"There is no exercise better for the heart than reaching down and lifting people up.",
		"Resolve to make each day the very best and don't let anyone get in your way. If they do, step on them.",
		"Believe those who are seeking the truth; doubt those who find it.",
		"In the book of life, the answers aren't in the back.",
		"A man who makes trouble for others is also making trouble for himself.",
		"I came, I saw, I conquered.",
		"Just surrender to the cycle of things, Give yourself to the waves of the Great Change, And when it is time to go, then simply go, Without any unnecessary fuss.",
		"We encounter the grinding wheels that sharpen our mental blades many places in life. Adversity, school, parents, spiritual guides, books, experience are all sharpening teachers. As we grow older, to stay sharp we must find new grindstones to whet and sharpen our potential and keep us at our brightest, most penetrating best.",
		"His best companions, innocence and health; And his best riches, ignorance of wealth.",
		"To fly, we have to have resistance.",
		"Never fear shadows. They simply mean that there's a light somewhere nearby.",
		"One friend in a lifetime is much; two are many; three are hardly possible.",
		"I either want less corruption, or more chance to participate in it.",
		"God grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.",
		"There is a great disturbance in the force.",
		"To fly, we have to have resistance.",
		"O, what a tangled web we weave, when first we practise to deceive.",
		"Reason often makes mistakes, but conscience never does.",
		"Life moves pretty fast, If you don't take a look around once and awhile, you could miss it.",
		"Life is as a jelly roll. When you think you have it eaten, it comes out the other end.",
		"No animal is so inexhaustable as an excited infant.",
		"Leftovers in their less visible form are called memories. Stored in the refrigerator of the mind and the cupboard of the heart.",
		"There was a time when a fool and his money were soon parted, but now it happens to everybody.",
		"We ought to do good to others as simply as a horse runs, or a bee makes honey, or a vine bears grapes season after season without thinking of the grapes it has borne.",
		"There wouldn't be a sky full of stars if we were all meant to wish on the same one.",
		"Setting an example for your children takes all the fun out of middle age. Conditions are never just right. People who delay action until all factors are favorable do nothing.",
		"Nobody can be so amusingly arrogant as a young man who has just discovered an old idea and thinks it is his own.  When I hear somebody sigh, Life is hard, I am always tempted to ask, Compared to what?",
		"Take time to deliberate; but when the time for action arrives, stop thinking and go in. One man with courage makes a majority.",
		"Of those who say nothing, few are silent.",
		"When we walk to the edge of all the light we have and take the step into the darkness of the unknown, we must believe that one of two things will happen. There will be something solid for us to stand on or we will be taught to fly.",
		"Life is the acceptance of responsibilities or their evasion, it is a business of meeting obligations or avoiding them. To every man the choice is continually being offered, and by the manner of his choosing you may fairly measure him.",
		"How do I know that love of life is not a delusion after all? How do I know that he who dreads death is not as a child who has lost his way and does not know his way home?",
		"A little inaccuracy sometimes saves a ton of explanation.",
		"Age does not diminish the extreme disappointment of having a scoop of ice cream fall from the cone.",
		"The future you shall know when it has come; before then, forget it.",
		"Perhaps the truth depends on a walk around the lake.",
		"The robbed that smiles, steals something from the thief.",
		"We cannot waste time.  We can only waste ourselves.",
		"There's never enough time to do all the nothing you want.",
		"If you don't know where you are going, you will probably end up somewhere else.",
		"Fall seven times, stand up eight.",
		"Let us be of good cheer, remembering that the misfortunes hardest to bear are those which will never happen.",
		"One problem with gazing too frequently into the past is that we may turn around to find the future has run out on us.",
		"The first sign of maturity is the discovery that the volume knob also turns to the left.",
		"If they give you ruled paper, write the other way.",
		"Beer is proof that God loves us and wants us to be happy.",
		"Time and memory are true artists; they remould reality nearer to the heart's desire.",
		"I have discovered that all human evil comes from this, man's being unable to sit still and quiet in a room alone.",
		"When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.",
		"The worst bankrupt in the world is the person who has lost his enthusiasm.",
		"Imagination is the highest kite one can fly.",
		"Think it more satisfactory to live richly than die rich.",
		"To live is so startling it leaves little time for anything else.",
		"Stop a moment, cease your work, and look around you.",
		"Regret for the things we did can be tempered by time; it is regret for the things we did not do that is inconsolable.",
		"A solitary, unused to speaking of what he sees and feels, has mental experiences which are at once more intense and less articulate than those of a gregarious man.",
		"I don't know what you could say about a day in which you have seen four beautiful sunsets.",
		"I don't know what you could say about a day in which you have seen four beautiful sunsets.",
		"It is a revenge the devil sometimes takes upon the virtuous, that he entraps them by the force of the very passion they have suppressed and think themselves superior to.",
		"You have not converted a man because you have silenced him.",
		"Everything flows; nothing remains.",
		"All commend patience, but none can endure to suffer.",
		"Money, the root of all evil...but the cure for all sadness.",
		"Advice is like snow -- the softer it falls, the longer it dwells upon, and the deeper in sinks into the mind.",
		"People generally quarrel because they cannot argue.",
		"He who angers you conquers you.",
		"The marvelous richness of human experience would lose something of rewarding joy if there were no limitations to overcome. The hilltop hour would not be half so wonderful if there were no dark valleys to traverse.",
		"Beware of the man who does not talk, and the dog that does not bark.",
		"For small creatures such as we the vastness is bearable only through love.",
		"Your life is the sum result of all the choices you make, both consciously and unconsciously. If you can control the process of choosing, you can take control of all aspects of your life. You can find the freedom that comes from being in charge of yourself.",
		"Habit and routine have an unbelievable power to waste and destroy.",
		"Life is the art of drawing sufficient conclusions from insufficient premises.",
		"To be what we are, and to become what we are capable of becoming, is the only end of life.",
		"All that we see or seem is but a dream within a dream.",
		"Life is like music; it must be composed by ear, feeling, and instinct, not by rule.",
		"Real poverty is less a state of income than a state of mind.",
		"You can't put the toothpaste back in the tube.",
		"We are most nearly ourselves when we achieve the seriousness of the child at play.",
		"Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.",
		"The nice thing about egoists is that they don't talk about other people.",
		"Before the gates of excellence the high gods have placed sweat; long is the road thereto and rough and steep at first; but when the heights are reached, then there is ease, though grievously hard in the winning.",
		"Too often we give our children answers to remember rather than problems to solve.",
		"The only thing that makes life possible is permanent, intolerable uncertainty; not knowing what comes next.",
		"Paranoia is reality on a finer scale.",
		"It is only imperfection that complains of what is imperfect.  The more perfect we are, the more gentle and quiet we become toward the defects of others.",
		"I have never in my life learned anything from any man who agreed with me.",
		"Go thy way, eat thy bread with joy, and drink thy wine with a merry heart; for God now accepteth thy works.",
		"A competent and self-confident person is incapable of jealousy in anything. Jealousy is invariably a symptom of neurotic insecurity.",
		"I believe that if you think about disaster, you will get it. Brood about death and you hasten your demise. Think positively and masterfully with confidence and faith, and life becomes more secure, more fraught with action, richer in achievement and experience.",
		"My research consists of studying the effects of putting somebody like me into a world like this.",
		"Whatever the theories may be of woman's dependence on man, in the supreme moments of her life he can not bear her burdens.",
		"Sun illuminates only the eye of the man, but shines into the eye and heart of the child.",
		"Most of us don't know what we want and spend our lives wondering why we don't get it.",
		"Each has his past shut in him like the leaves of a book known to him by heart and his friends can only read the title.",
		"A good time to keep your mouth shut is when you're in deep water.",
		"People change, not necessarily in negative ways. Sometimes goals and intentions in life aren't aligned. It's just choices we make in life. Otherwise, why aren't we with the person we were with in seventh grade?",
		"From what we get, we can make a living; what we give, however, makes a life.",
		"For fast acting relief ;  try slowing down.",
		"The trouble with our times is that the future is not what it used to be.",
		"We are not permitted to choose the frame of our destiny. But what we put into it is ours.",
		"One can know a man from his laugh, and if you like a man's laugh before you know anything of him, you may confidently say that he is a good man.",
		"Silence is exhilarating at first--as noise is--but there is a sweetness to silence outlasting exhilaration, akin to the sweetness of listening and the velvet of sleep.",
		"When people are free to do as they please, they usually imitate each other.",
		"Time makes more converts than reason.",
		"There is only one success: to be able to spend your life in your own way, and not to give others absurd maddening claims upon it.",
		"The bigger the real-life problems, the greater the tendency for the discipline to retreat into a reassuring fantasy-land of abstract theory and technical manipulation.",
		"No man means all he says, and yet very few say all they mean, for words are slippery and thought is viscous.",
		"The age span 16-30 is crucial, for that is the period when life adds sweetness to itself, when talents, skills and attitudes are accumulated, sublimated, and sanctified. If the tonic of unselfish service is administered to the mind during this period, life mission is fulfilled - for the process of sublimation and sanctification will be hastened by this tonic.",
		"Probably the happiest period in life most frequently is in middle age, when the eager passions of youth are cooled, and the infirmities of age not yet begun; as we see that the shadows, which are at morning and evening so large, almost entirely disappear at midday.",
		"The universe is made of stories, not of atoms.",
		"It has long been an axiom of mine that the little things are infinitely the more important.",
		"While we are free to choose our actions, we are not free to choose the consequences of our actions.",
		"My advice to people today is as follows: If you take the game of life seriously, if you take your nervous system seriously, if you take your sense organs seriously, if you take the energy process seriously, you must turn on, tune in, and drop out.",
		"There are three ingredients in the good life: learning, earning and yearning.",
		"Few are those who see with their own eyes and feel with their own hearts",
		"There is only one success: to be able to spend your life in your own way, and not to give others absurd maddening claims upon it.",
		"It is sufficiently clear that all things are changed, and nothing really perishes, and that the sum of matter remains absolutely the same.",
		"The road up and the road down are one and the same.",
		"The badge of honesty. Having it lets you look at any man in the eye. Lacking it he won't look back. Keep this one at the top of your list.",
		"May the road rise to meet you. May the wind always be at your back. May the sun shine warm upon your face, the rains fall soft upon your fields, and, until we meet again, may God hold you in the palm of his hand.",
		"The fellow who thinks he knows it all is especially annoying to those of us who do.",
		"None are more hopelessly enslaved than those who falsely believe they are free.",
		"Women and cats will do as they please and men and dogs should relax and get used to the idea.",
		"Advice is what we ask for when we already know the answer but wish we didn't.",
		"Those who are awake all live in the same world. Those who are asleep live in their own worlds.",
		"The only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn, like fabulous yellow roman candles exploding like spiders across the stars and in the middle you see the blue centerlight pop and everybody goes 'Awww!'",
		"We grow small trying to be great.",
		"Natives who beat drums to drive off evil spirits are objects of scorn to smart Americans who blow horns to break up traffic jams.",
		"He who joyfully marches to music in rank and file has already earned my contempt. He has been given a large brain by mistake.  For him the spinal cord alone would fully suffice.",
		"Until now, modes of life have been based on the material servitude of the mass of people. Intellectual exploration, intellectual creativity, and the substance of personal freedom have been limited to minorities of the population. Intellectual exploration as a paid job has been limited to accredited social élites.",
		"The world is made of people who never quite get into the first team and who just miss the prizes at the flower show.",
		"The society of merchants can be defined as a society in which things disappear in favor of signs. When a ruling class measures its fortunes, not by the acre of land or the ingot of gold,but by the number of figures corresponding ideally to a certain number of exchange operations, it thereby condemns itself to setting a certain kind of humbug at the center of its experience and its universe. A society founded on signs is, in its essence, an artificial society in which man'scarnal truth is handled as something artificial.",
		"It has become appallingly obvious that our technology has exceeded our humanity.",
		"One death is a tragedy.  A million deaths is a statistic.",
		"People demand freedom of speech as a compensation for the freedom of thought which they never use.",
		"Heredity is a splendid phenomenon that relievesus of responsibility for our shortcomings.",
		"We take what we want and leave the rest,just like your salad bar.",
		"Only dead fish go with the current.",
		"Aristotle taught that the brain exists merely to cool the bloodand is not involved in the process of thinking.  This is true only of certain persons.",
		"As long as people will accept crap, it will be financially profitable to dispense it.",
		"The secret of being tiresome is to tell everything.",
		"It has been my experience that folks who have no vices have few virtues.",
		"Putting it in plain terms, the general public must be reduced to its traditional apathy and obedience, and driven from the arena of political debate and action, if democracy is to survive.",
		"You cannot strengthen the weak by weakening the strong. You cannot help small men by tearing down big men.  You cannot help the poor by destroying the rich. You cannot lift the wage earner by pulling down the wage-payer.  You cannot keep out of trouble by spending more than your income. You cannot further the brotherhood of man by inciting class hatreds. You cannot build character and courage by taking away a man's initiative and independence. You cannot help men permenantly by doing for them what they could and should do for themselves.",
		"The invention of the teenager was a mistake. Once you identify a period of life in which people get to stay out late but don't have to pay taxes - naturally, nobody wants to live any other way.",
		"Ten people who speak make more noise than ten thousand who are silent.",
		"It is natural to man to indulge in the illusion of hope. We are apt to shut our eyes against the painful truth, and listen to the song of that siren, till she transforms us into beasts.",
		"The concept of progress acts as a protective mechanism to shield us from the terrors of the future.",
		"Our crude civilization engenders a multitude of wants, and law-givers are ever at their wit's enddevising.  The hall and the theater and the church have been invented, and compulsory education.  Why not add compulsory recreation? Our forefathers forged chains of duty and habit, which bindus notwithstanding our boasted freedom, and we ourselves in desperation add link to link,groaning and making medicinal laws for relief. Yet few think of pure rest or of the healing powerof Nature.",
		"And what does the money machine eat to shit out? It eats youth, spontaneity, life, beauty and above all it eats creativity. It eats quality and shits out quantity.",
		"The world acquires value only through its extremes and endures only through moderation; extremists make the world great, the moderates give it stability.",
		"To talk much and arrive nowhere is the same as climbing a tree to catch a fish.",
		"There can be no truth since truth varies with different individuals and with each individual in different circumstances; there can be no communication with others because words interpret what seems to be and not what is; and, in the last resort, there can be no sanity since sanity demands a stable foundation.",
		"If all mankind minus one were of one opinion, mankind would be no more justified in silencing that one person than he, if he had the power, would be justified in silencing mankind.",
		"Anyone who cannot cope with mathematics is not fully human. At best he is a tolerable subhuman who has learned to wear shoes, bathe, and not make messes in the house.  Time Enough for Love.",
		"The hallmark of our age is the tension between aspirations and sluggish institutions.",
		"The monster of advertisement. . . is a sort of octopus with innumerable tentacles. It. . . gathers in, through its thousand little suckers, all the gossip and slander and praise afloat, to spit out again at the public.'",
		"I praise loudly, I blame softly.",
		"Great men are they who see that spiritual is stronger than any material force, that thoughts rule the world.",
		"A man who keeps his word is worth much more.",
		"Human felicity is produced not so much by great pieces of good fortune that seldom happen, as by little advantages that occur each day.",
		"We are all in the gutter, but some of us are looking at the stars.",
		"Good sense is, of all things among men, the most equally distributed; for every one thinks himself so abundantly provided with it, that those even who are the most difficult to satisfy in everything else, do not usually desire a larger measure of this quality than they already possess.",
		"Many that live deserve death. And some that die deserve life. Can you give it to them?  Then do not be too eager to deal out death in judgement. For even the very wise cannot see all ends.",
		"Wave upon wave of demented avengers march cheerfully out of obscurity into the dream. Have you heard the news?  The dogs are dead. You'd better stay home and do as you're told. Get out of the road if you wanna grow old.",
		"Finding a cure for cancer and heart disease would be a major financial disaster which would bankrupt the social security system and the big insurance companies.",
		"When you have once seen the glow of happiness on the face of a beloved person, you know that a man can have no vocation but to awaken that light on the faces surrounding him; and you are torn by the thought of the unhappiness and night you cast, by the mere fact of living, in the hearts you encounter.",
		"The present state of the world and the whole of life is diseased. If I were a doctor and were asked for my advice, I should reply: Create Silence.",
		"Nobody realizes that some people expend tremendous energy merely to be normal.",
		"It does no harm just once in a while to acknowledge that the whole country isn't in flames, that there are people in the country besides politicians, entertainers, and criminals.",
		"Half the troubles of mankind come from ignorance, -- ignorance which is systematically organized with societies for its support and newspapers for its dissemination, -- ignorance which consists less in not knowing things, than in willfully ignoring the things that are already known.",
		"It may be true that the law cannot make a man love me. But it can keep him from lynching me, and I think that's pretty important.",
		"It's no measure of health to be well adjusted to a profoundly sick society.",
		"Advertising isn't a science. It's persuasion. And persuasion is an art.",
		"An economist is an expert who will know tomorrow why the things he predicted yesterday didn't happen today.",
		"The urbane activity which a man receives money is really marvellous, considering that we so earnestly believe money to be the root of all earthly ills, and that on no account can a monied man enter heaven.  Ah! how cheerfully we consign ourselves to perdition!",
		"The great curse of our modern society is not so much the lack of money as the fact that the lack of money condemns a man to a squalid and incomplete existence.",
		"So far as I can see, the atomic bomb has deadened the finest feeling that has sustained humankind for ages... The moral to be legitimately drawn from the supreme tragedy of the bomb is that it will not be destroyed by counter-bombs, even violence cannot be by counter-violence. Human kind has to get out of violence only through nonviolence. Hatred can be overcome only by love. Counter-hatred only increases the surface as well as the depth of hatred.",
		"America has no north, no south, no east, no west. The sun rises over the hills and sets over the mountains, the compass just points up and down, and we can laugh now at the absurd notion of there being a north and a south. We are one and undivided.",
		"The true measure of a man is how he treats someone who can do him absolutely no good.",
		"Expecting the world to treat you fairly because you are a good person is a little like expecting a bull not to attack you because you are a vegetarian.",
		"We are living in a world today where lemonade is made from artificial flavors and furniture polish is made from real lemons...",
		"Those who stand for nothing fall for anything.",
		"The populace is by nature fickle. It is easy to persuade them of something, but very difficult to confirm them in that persuasion.",
		"There is nothing more uncommon than common sense.",
		"So many gods, so many creeds, So many paths that wind and wind, While just the art of being kind is all the sad world needs.",
		"Capitalism is the extraordinary belief that the nastiest of men, for the nastiest of reasons, will somehow work for the benefit of us all.",
		"Man walks the moon but his soul remains riveted to earth.  Once upon a time it was the opposite.",
		"The amount of noise which anyone can bear undisturbed stands in inverse proportion to his mental capacity.",
		"Hypocrisy is the lubricant of society.",
		"In Germany they came first for the Communists, and I didn't speak up because I wasn't a Communist. Then they came for the Jews, and I didn't speak up because I wasn't a Jew. Then they came for the trade unionists, and I didn't speak up because I wasn't a trade unionist. Then they came for the Catholics, and I didn't speak up because I was a Protestant. Then they came for me, and by that time no one was left to speak up.",
		"Man has made use of his intelligence, he invented stupidity.",
		"Nothing is too high for the daring of mortals: we storm heaven itself in our folly.",
		"If triangles had a God, He'd have three sides.",
		"(In regards to China) 'To trade with them is actually more corrosive than not.'",
		"When we get piled upon one another in large cities, as in Europe, we shall become as corrupt as Europe.",
		"We Arabs, especially the educated among us, look with deepest sympathy on the Zionist movement... We will wish the Jews a hearty welcome home... We are working together for a reformed and revised Near East, and our two movements complement one another. The movement is national and not imperialistic. There is room in Syria for us both. Indeed, I think that neither can be successful without the other.",
		"They will say you are on the wrong road, if it is your own.",
		"In every country where man is free to think and to speak, differences of opinion will arise from difference of perception, and the imperfection of reason; but these differences when permitted, as in this happy country, to purify themselves by free discussion, are but as passing clouds overspreading our land transiently and leaving our horizon more bright and serene.",
		"Football combines two of the worst things about American life.  It is violence punctuated by committee meetings.",
		"Nothing is wrong with California that a rise in the ocean level wouldn't cure.",
		"The release of atomic energy has not created a new problem. It has merely made more urgent the necessity of solving an existing one.",
		"Some people like my advice so much that they frame it upon the wall instead of using it.",
		"The chief product of an automated society is a widespread and deepening sense of boredom.",
		"Money never made a man happy yet, nor will it. There is nothing in its nature to produce happiness. The more a man has, the more he wants. Instead of its filling a vacuum, it makes one.",
		"You do not destroy an idea by killing people; you replace it with a better one.",
		"As far as we can discern, the sole purpose of human existence is to kindle a light in the darkness of mere being.",
		"Only the wisest and the stupidest of men never change.",
		"Those that can give up essential liberty to obtain a little temporary safety deserve neither liberty nor safety.",
		"A true leader is hated by most, and respected by all. A follower is liked by all, and respected by none.",
		"Madness is rare in individuals; but in groups, political parties, nations, and eras it's the rule.",
		"A classic is something that everybody wants to have read and nobody wants to read.",
		"Any society that needs disclaimers has too many lawyers.",
		"What fools these mortals be.(Tanta Stultitia Mortalium Est.)",
		"Speak only well of people and you need never whisper.",
		"Few of us will have the greatness to bend history itself, but each of us can work to change a small portion ofevents, and in the total of these acts will be written the history of this generation.",
		"Nothing... is unchangeable but the inherent and inalienable rights of man.",
		"Men willingly believe what they wish.",
		"Anyone can hold the helm when the sea is calm.",
		"The human mind treats a new idea the same way the body treats a strange protein; it rejects it.",
		"Before God we are all equally wise - and equally foolish.",
		"The future, according to some scientists, will be exactly like the past, only far more expensive.",
		"America may be unique in being a country which has leapt from barbarism to decadence without touching civilization.",
		"Never attribute to malice what can be adequately explained by stupidity.",
		"What a blessing it would be if we could open and shut our ears as easily as we open and shut our eyes!",
		"You probably wouldn't worry about what people think of you if you could know how seldom they do.",
		"I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use.",
		"Everybody lies, but it doesn't matter because nobody listens.",
		"The pure and simple truth is rarely pure and never simple.",
		"The meek shall inherit the Earth, but not its mineral rights.",
		"Boys will be boys, and so will a lot of middle-aged men.",
		"If God lived on earth, people would break his windows.",
		"The optimist thinks this is the best of all possible worlds. The pessimist fears it is true.",
		"You white people are so strange. We think it is very primitive for a child to have only two parents.",
		"The very powerful and the very stupid have one thing in common. Instead of altering their views to fit the facts, they alter the facts to fit their views",
		"No one ever went broke underestimating the taste of the American public.",
		"There are no exceptions to the rule that everybody likes to be an exception to the rule.",
		"Anyway, no drug, not even alcohol, causes the fundamental ills of society. If we're looking for the source of our troubles, we shouldn't test people for drugs, we should test them for stupidity, ignorance, greed and love of power.",
		"Man is the only animal that learns by being hypocritical. He pretends to be polite and then, eventually, he becomes polite.",
		"Speak only well of people and you need never whisper.",
		"Few of us will have the greatness to bend history itself, but each of us can work to change a small portion of events, and in the total of these acts will be written the history of this generation.",
		"Nothing... is unchangeable but the inherent and inalienable rights of man.",
		"Before God we are all equally wise - and equally foolish.",
		"What a blessing it would be if we could open and shut our ears as easily as we open and shut our eyes!",
		"I do not feel obliged to believe that the same God who has endowed us with sense, reason, and intellect has intended us to forgo their use.",
		"If God lived on earth, people would break his windows.",
		"The dynamics of capitalism is postponement of enjoyment to the constantly postponed future.",
		"A market is the combined behavior of thousands of people responding to information, misinformation and whim."];

	    var json = {"quotes" : quotes};

	    processJson(json);
	},

	sendQuote = function() {
	    if (sockets.length) {
		var randomQuoteIndex = Math.floor(Math.random() * data.quotes.length);
		for (i=0; i<sockets.length; i++) {
		    try {
			sockets[i].send(JSON.stringify(data.quotes[randomQuoteIndex]));
		    } catch (e) {
			console.log(e);
		    }
		}
	    }
	},

	processJson = function(json) {
	    data = json;
	    sendQuote();
	    timerID = setInterval(sendQuote, 5000);

	},

	init = function(httpPort, socketPort) {
	    httpListen(httpPort);
	    socketListen(socketPort);
	};

    return {
	init: init
    };
 
}();

module.exports = socketServer;
